### ISSUE TITLE
Weekly Scrum - March 21st 2021

### ISSUE THREAD

**Issue by Samuel-Baumann** [omarazam98/BookStore_4806-SwingBoot_Firebase#12]
What have I done?

Reviewed feedback to organize Kanban / process
Familiarized myself more with Git and Content

What am I going to do next week?

Commit vertical slices as recommended by Jason
Implement Owner aspect of User class
Be sad

What is holding me back?

My deepest fears

**Comment by mackhoyle** [comment]
Test

**Comment by davidneale** [comment]
What have I done?

Reviewed feedback to organize Kanban board into Projects tab
Updated Issues tab to allow for a feature-based work assignment

What am I going to do next week?
Work on issues: Implement a bookstore Owner (https://github.com/omarazam98/BookStore_4806-SwingBoot_Firebase/issues/15#issue-837231920)

What is holding me back?
Issues with Git branches from forked repo not showing up in main repo

**Comment by mackhoyle** [comment]
What have I done?

Researched how we should implement code reviews. 

What am I going to do next week?
Add Purchased Book Controller

What is holding me back?
Getting familar with building templates.
