### ISSUE TITLE
Weekly Scrum - March 11th 2021

### ISSUE THREAD

**Issue by omarazam98** [omarazam98/BookStore_4806-SwingBoot_Firebase#2]
What I have Done?
- Initialized Repository 
- Created and Connected Firebase Database
- Created Login/Signup - Controllers/Models/Views
- Configured Heroku and Travis CI

What am I going to do next week?
- Create shopping cart controllers/Models/Templates
- Create shopping cart database query's

What is holding me back?
- Nothing

**Comment by Samuel-Baumann** [comment]
What have I done this week
-Achieved familiarity in Git
-Bookstore model & Controller

What will I do next week
-Coordinate keep all members on the same page
-Stare slack-jawed into the distance

What is holding me back
-Getting comfortable using version control
-Deepening understanding of Spring Boot and associated techniques

**Comment by mackhoyle** [comment]
What I have done?

- Created the necessary test folders and test files for our home and book controllers.
- Created tests for each endpoint in our controllers.

What am I going to do next week?

- Continue adding tests for the controllers. 
- Add more books into our database.

What is holding me back?

- Getting familiar with testing controllers in spring boot.

**Comment by davidneale** [comment]
What have I done this week?

- Achieved some familiarity in Git
- Created UML Class Diagram
- Created Database Schema

What will I do next week?

- Continue adding to the diagrams
- More TBD at next scrum

What is holding me back?

- Lack of familiarity with correct usage of version control
