### ISSUE TITLE
Weekly Scrum - March 25th 2021

### ISSUE THREAD

**Issue by Samuel-Baumann** [omarazam98/BookStore_4806-SwingBoot_Firebase#20]
What have I done?

Reviewed Code and commits from other members
Revamped UML Diagrams and tables
Created basic tests

What am I going to do next week?

Work on recommendation system
Look into ORM Alternatives and apply to project

What is holding me back?

Several metric tons of a steel-aluminum composite alloy that has been surgically attached to my sternum, preventing all movement and severely inhibiting breathing / bodily functions

**Comment by davidneale** [comment]
What have I done?

Reviewed Code and commits from other members
Implemented "Owner" functionality - solving issue #15 
What am I going to do next week?

Continue updating "Owner" usability
Look into ORM Alternatives and work with the team to apply to the project

What is holding me back?

hiccups from git are mostly cleared but still needs some work
finding time among hectic semester to allocate to the project

**Comment by mackhoyle** [comment]
What have I done?

Implemented Purchased Book Controller

What am I going to do next week?

Add Recommendations To the Purchased Books

What is holding me back?

Takes a long time to debug something cause you have to run the app every time you make a change
